### ISSUE TITLE
KeyError: 'quoteId'

### ISSUE THREAD

**Issue by dev590t** [rklf/paybybot3#8]
I'm try running paybybot3:
```
$ paybybot3 pay --rate 2 --location  75012 --duration 1minutes example_account
```

I get the error:
```
2024-05-21 23:54:40,068 - root - INFO - created bot
2024-05-21 23:54:40,069 - root - INFO - launching payment
2024-05-21 23:54:41,171 - root - ERROR - _pay
Traceback (most recent call last):
  File "/home/dev_1/.local/lib/python3.10/site-packages/paybybot3/__main__.py", line 20, in wrapper
    return fun(*args, **kwargs)
  File "/home/dev_1/.local/lib/python3.10/site-packages/paybybot3/__main__.py", line 164, in _pay
    bot.pay(
  File "/home/dev_1/.local/lib/python3.10/site-packages/paybybot3/bot.py", line 205, in pay
    quoteId = quote["quoteId"]
KeyError: 'quoteId'
2024-05-21 23:54:41,296 - apprise - WARNING - Invalid ~From~ email specified: PayByBot3 <>
2024-05-21 23:54:41,297 - apprise - ERROR - Could not load E-Mail URL: mailtos://{user}:{password}@{domain}?name=PayByBot3
2024-05-21 23:54:41,297 - root - ERROR - Error sending notification: 'str' object has no attribute 'values'
```

Why I get `KeyError: 'quoteId'`? I'm not sure I have used `--rate` and `--duration` correctly

**Comment by HamletDuFromage** [comment]
https://github.com/rklf/paybybot3/blob/173d59c87bd246fc78c5511f56f1a01d95cf4533/paybybot3/__main__.py#L166

Looks like the default is "Days" without a proper way to change it from the command line. As it stands, `--duration` only accepts numbers. I wonder if a fraction would work

It'd be pretty straight forward to add a cli argument to specify units. Let me know if you're interested, then you can test it and I'll submit a PR

**Comment by dev590t** [comment]
> It'd be pretty straight forward to add a cli argument to specify units. Let me know if you're interested, then you can test it and I'll submit a PR

@HamletDuFromage , thank you. I think it is a interesting feature. I'm glad to test this feature.

But my main problem is I can't run `paybybot3` to buy a ticket, even with correct `--duration` parameter:
`paybybot3 pay --rate 2 --location  75012 --duration 1 example_account`. I get the same error.

**Comment by HamletDuFromage** [comment]
You'd probably have to debug it, printing out `quote` to look for its content/error message and work your way up. Chances are your config isn't right

**Comment by dev590t** [comment]
> You'd probably have to debug it, printing out `quote` to look for its content/error message and work your way up. Chances are your config isn't right

Thank you, you are right!
In the configuration, for `plate`, I have follow the format of the example in README: `XXDDDXX`. But in `paybybot3 vehicles example_account`, the format is `XX DDD XX`. That is why that fails.

**Comment by HamletDuFromage** [comment]
@dev590t feel free to try this out when you get the occasion https://github.com/HamletDuFromage/paybybot3

I don't see why it wouldn't work, the api does expect `durationTimeUnit=Minutes` but I haven't actually done a real test

**Comment by dev590t** [comment]
@HamletDuFromage , yes, I will try it.
